---
dependency:
  name: galaxy
driver:
  name: ec2
lint:
  name: yamllint
platforms:
  - name: Debian
    groups:
      - molecule
    image: ami-018d4a384e91e09a0
    instance_type: t2.micro
    vpc_subnet_id: subnet-02c842fabb57e1b51
    region: "us-east-1"
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
verifier:
  name: testinfra
  lint:
    name: flake8
    