---
- name: install epel-release
  yum:
    pkg: epel-release
    state: latest

- name: install php71
  yum:
    pkg: php71
    state: latest

- name: install php-fpm
  yum:
    pkg: php-fpm
    state: latest

- name: install yum-utils
  yum:
    pkg: yum-utils
    state: latest
    
- name: Add Nginx Repository
  copy: src=nginx.repo dest=/etc/yum.repos.d/ owner=root group=root
  register: nginx_repo

#- name: --enable nginx-mainline
#  shell: yum-config-manager --enable nginx-mainline

- name: Install Nginx
  yum: 
    pkg: nginx 
    state: latest

- name: Add NGINXcofig
  template: src=main.j2 dest=/etc/nginx/conf.d/{{ ports }}.conf owner=nginx group=nginx

- name: Create symlink nginx
  file:
    src=main.j2
    dest={{ nginx_links }}/{{ ports }}.conf
    state=link
  notify: restart nginx

- name: Create Web Root
  file: path={{ root }}  mode=775 state=directory owner=nginx group=nginx
  notify:
    - nginx restart
