---
- name: Install packet gnupg2
  apt: 
    name: gnupg2 
    state: present
- name: install ca-certificates
  apt: 
    name: ca-certificates 
    state: present
- name: install lsb-release
  apt: 
    name: lsb-release 
    state: present
- name: add repo
  shell: echo deb http://nginx.org/packages/mainline/ubuntu bionic nginx | sudo tee /etc/apt/sources.list.d/nginx.list
- name: add key
  shell: curl -fsSL https://nginx.org/keys/nginx_signing.key | sudo apt-key add -
- name: Add an Apt nginx_signing
  apt_key:
    id: ABF5BD827BD9BF62 
    url: https://nginx.org/keys/nginx_signing.key 
    state: present
- name: install nginx
  apt: 
    name: nginx
    state: present   
# -----------------------------------------------
- name: Add NGINXcofig
  template:
    src: "{{ item }}.conf.j2"
    dest: /etc/nginx/conf.d/{{ item }}.conf
    owner: root 
    group: root
  loop:
    - server1
    - server2
    - server3
  vars:
    - servername: "{{ item }}"
# -----------------------------------------------
- name: Create symlink s1
  file:
    src: /etc/nginx/conf.d/server1.conf
    dest: /etc/nginx/sites-enabled/server1.conf
    state: link
- name: Create symlink s2
  file:
    src: /etc/nginx/conf.d/server2.conf
    dest: /etc/nginx/sites-enabled/server2.conf
    state: link
- name: Create symlink s3
  file:
    src: /etc/nginx/conf.d/server3.conf
    dest: /etc/nginx/sites-enabled/server3.conf
    state: link
    