---
# tasks file for ftprole
- name: Include OS-specific variables
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
        - fallback.yml
      paths:
        - vars
  tags:
    - always

- name: Install YUM packages
  yum:
    name: '{{ pyenv_packages }}'
    state: present
    update_cache: true
  when: ansible_os_family == 'RedHat'

- name: Install APT packages
  apt:
    name: '{{ pyenv_packages }}'
    state: present
    update_cache: true
  when: ansible_os_family == 'Debian'
