---
- hosts: all
  gather_facts: false  

  become: yes

  vars:
    apps:
    - epel-release
    - vim
    - htop

  tasks:
    - name: Install epel-release
      yum:
        name:   epel-release
        state:  latest
    - name: Install vim, htop
      yum:
        name:   "{{ apps }}"
        state:  latest